// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AudioStream: typeof import('./src/components/media/AudioStream.vue')['default']
    AudioStreamer: typeof import('./src/components/stream/AudioStreamer.vue')['default']
    AutoAvatar: typeof import('./src/components/AutoAvatar.vue')['default']
    BottomBar: typeof import('./src/components/controllers/BottomBar.vue')['default']
    ChatTab: typeof import('./src/components/controllers/ChatTab.vue')['default']
    GroupChat: typeof import('./src/components/room/GroupChat.vue')['default']
    JoinConfirm: typeof import('./src/components/controllers/JoinConfirm.vue')['default']
    KeyMoment: typeof import('./src/components/room/KeyMoment.vue')['default']
    KickOut: typeof import('./src/components/controllers/KickOut.vue')['default']
    ListUserItem: typeof import('./src/components/controllers/ListUserItem.vue')['default']
    ListUserTab: typeof import('./src/components/controllers/ListUserTab.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    MainView: typeof import('./src/components/MainView.vue')['default']
    MatrixRoom: typeof import('./src/components/MatrixRoom.vue')['default']
    NavigationBar: typeof import('./src/components/room/NavigationBar.vue')['default']
    NavigationButton: typeof import('./src/components/includes/NavigationButton.vue')['default']
    RoomContainer: typeof import('./src/components/room/RoomContainer.vue')['default']
    RoomPreview: typeof import('./src/components/room/RoomPreview.vue')['default']
    RoomSetting: typeof import('./src/components/room/RoomSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarItem: typeof import('./src/components/room/SidebarItem.vue')['default']
    SidebarView: typeof import('./src/components/room/SidebarView.vue')['default']
    SpeakingSpinner: typeof import('./src/components/media/SpeakingSpinner.vue')['default']
    UserSlide: typeof import('./src/components/room/UserSlide.vue')['default']
    UserSlideItem: typeof import('./src/components/includes/UserSlideItem.vue')['default']
    UsersPreview: typeof import('./src/components/room/UsersPreview.vue')['default']
    VideoStream: typeof import('./src/components/media/VideoStream.vue')['default']
    VideoStreamer: typeof import('./src/components/stream/VideoStreamer.vue')['default']
  }
}
